# Generated by Django 3.1.1 on 2022-03-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='tipo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='animais',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
