# Generated by Django 3.1.1 on 2022-03-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_auto_20220322_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animais',
            old_name='tipo',
            new_name='domestico',
        ),
        migrations.RenameField(
            model_name='animais',
            old_name='nome',
            new_name='nome_animal',
        ),
        migrations.RenameField(
            model_name='animais',
            old_name='caracteristicas',
            new_name='predador',
        ),
        migrations.AddField(
            model_name='animais',
            name='venenoso',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
